server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:minibankdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    platform: h2

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update  # Typically 'update' is preferred for development
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        envers:
          audit_table_suffix: "_AUD"
          revision_field_name: "REV"
          revision_type_field_name: "REVTYPE"
    open-in-view: true  # Ensures Hibernate is open for the duration of the view rendering

  main:
    allow-bean-definition-overriding: true

  security:
    user:
      name: user
      password: password

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.minibank: DEBUG
  file:
    name: minibank.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
